_target_: src.dataloaders.tasks.pretrain.MLM

name: mlm
max_length: 1560

# Augmentation
p_sequence_reverse_events: 0.2
p_sequence_shuffle_events: 0.2
p_sequence_shuffle_tokens: 0.1
p_sentence_drop_tokens: 0.01

# p_sequence_timecut: 0.0
# p_sequence_resample: 0.4
# p_sequence_abspos_noise: 0.1
# p_sequence_hide_background: 0.01
# p_sentence_drop_tokens: 0.01

# MLM specific options
mask_ratio: 0.3 #0.1