defaults:
  - _self_
  - /generate: "???"

# Values for the different experiments
seed: "???"
version: "???"
implementation: "???"
name: "???"

local_path: "."
user_path: "."

# checkpoint
ckpt_path: null