defaults:
  # - /data_new/corpus@corpus: no12_set
  # - /data_new/vocabulary@vocabulary: no12_set
  - /data_new/corpus@corpus: 100_set
  - /data_new/vocabulary@vocabulary: 100_set
  - /task@task: decoder #change hardcoded in base.py

_target_: src.dataloaders.datamodule.L2VDataModule

batch_size: 24 #64 ###assuming 1 million params
num_workers: 4 #8

### If you want to train the model on subsets of data
subset: False
subset_id: 0 #max 2